on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 8 */3 * *' # at 8:00 every 3 days

name: Notify for new federclimb courses
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: make run
