on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 8 * * *'

name: Parse federclimb courses
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go run main.go
